### PR TITLE
fixes #6, error: illegal IP address string passed to inet_pton

### LINKED ISSUE #6: error: illegal IP address string passed to inet_pton
I get this error when bots are trying to access my django site. Any idea how illegal IP address should be dealt with?
Internal Server Error: /
Traceback (most recent call last):
  File "/var/lib/openshift/5409d566e0b8cd8c7a0002b6/python/virtenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/var/lib/openshift/5409d566e0b8cd8c7a0002b6/python/virtenv/lib/python2.7/site-packages/easy_timezones/middleware.py", line 42, in process_request
    tz = db.time_zone_by_addr(ip)
  File "/var/lib/openshift/5409d566e0b8cd8c7a0002b6/python/virtenv/lib/python2.7/site-packages/pygeoip/__init__.py", line 583, in time_zone_by_addr
    ipnum = util.ip2long(addr)
  File "/var/lib/openshift/5409d566e0b8cd8c7a0002b6/python/virtenv/lib/python2.7/site-packages/pygeoip/util.py", line 39, in ip2long
    return int(binascii.hexlify(socket.inet_pton(socket.AF_INET6, ip)), 16)
error: illegal IP address string passed to inet_pton

### PR DESCRIPTION
**Pull request by vinitkumar**
The illegal IP usually comes up when the user is behind a proxy and gets comma separated values which might also have strings in it. We use this library in our project and faced this issue quite often. This fix works nicely for us and I hope for others too. Please take a look and merge if you are happy with the patch. 

Thanks!

### CODE REVIEW

**Comment by lucas03** [comment]
There is a different GEOIP database for IPv6 as far as I know - http://dev.maxmind.com/geoip/legacy/geolite/. I did not see it in your commit. Or am I wrong?

**Comment by vinitkumar** [comment]
@lucas03 you are right. I have not used the another database here and I was under the impression this same database has both ipv6 and ipv4 data. How do you suggest we take it forward?

**Comment by lucas03** [comment]
well there are 3 pull (although mine is too sloppy) requests already. I hoped Miserlou would take care of this by now, because it is deal breaker for every IPv6 visitors or robots. 
https://github.com/Miserlou/django-easy-timezones/pull/9

**Comment by pawciobiel** [comment]
@Miserlou do you need anything else for this fix to be merged & released?

**Comment by Miserlou** [comment]
Looks okay, but honestly I haven't touched this code in a long time and the whole project needs some upgrades - test cases, coverage, etc.

**Pull request merged**
